listkelurahan:
  kelurahan:
    - CIPAYUNG
    - CIPUTAT
    - JOMBANG
    - SAWAH BARU
    - SAWAH LAMA
    - SERUA
    - SERUA INDAH
    - CEMPAKA PUTIH
    - CIREUNDEU
    - PISANGAN
    - PONDOK RANJI
    - REMPOA
    - RENGAS
    - BAMBU APUS
    - KEDAUNG
    - PONDOK BENDA
    - PAMULANG BARAT
    - PAMULANG TIMUR
    - BENDA BARU
    - PONDOK CABE ILIR
    - PONDOK CABE UDIK
    - JURANGMANGU BARAT
    - JURANGMANGU TIMUR
    - PONDOK KACANG TIMUR
    - PONDOK KACANG BARAT
    - PERIGI LAMA
    - PERIGI BARU
    - PONDOK AREN
    - PONDOK KARYA
    - PONDOK JAYA
    - PONDOK BETUNG
    - PONDOK PUCUNG
    - BUARAN
    - CIATER
    - CILENGGANG
    - LENGKONG GUDANG
    - LENGKONG GUDANG TIMUR
    - LENGKONG WETAN
    - RAWA BUNTU
    - RAWA MEKAR JAYA
    - SERPONG
    - LENGKONG KARYA
    - PAKUALAM
    - JELUPANG
    - PAKU JAYA
    - PAKULONAN
    - PONDOK JAGUNG
    - PONDOK JAGUNG TIMUR
    - BABAKAN
    - BAKTI JAYA
    - KADEMANGAN
    - KERANGGAN
    - MUNCUL
    - SETU